version: 2

sources:
  - name: us_airline_delay_flights_delay

    database: us_airline_delay
    # schema: public
    tables:
      - name: flights_delay
        identifier: flights_delay
        description: "Table containing flight delay information."
        # columns:
        #   - name: fl_date
        #     description: "Date of flight."
        #     tests:
        #       - name: not_null
        #   - name: op_carrier
        #     description: "Operating airline code."
        #     tests:
        #       - name: not_null
        #   - name: op_carrier_fl_num
        #     description: "Operating airline flight number."
        #     tests:
        #       - name: not_null
        #   - name: origin
        #     description: "Origin airport code."
        #     tests:
        #       - name: not_null
        #   - name: dest
        #     description: "Destination airport code."
        #     tests:
        #       - name: not_null
        #   - name: crs_dep_time
        #     description: "Scheduled departure time."
        #     tests:
        #       - name: not_null
        #   - name: dep_time
        #     description: "Actual departure time."
        #     tests:
        #       - name: not_null
        #   - name: dep_delay
        #     description: "Delay at departure."
        #     tests:
        #       - name: not_null
        #   - name: taxi_out
        #     description: "Time between departure from the gate and wheels off."
        #     tests:
        #       - name: not_null
        #   - name: wheels_off
        #     description: "Actual time when wheels leave the ground."
        #     tests:
        #       - name: not_null
        #   - name: wheels_on
        #     description: "Actual time when wheels touch the ground."
        #     tests:
        #       - name: not_null
        #   - name: taxi_in
        #     description: "Time between wheels on and arrival at the gate."
        #     tests:
        #       - name: not_null
        #   - name: crs_arr_time
        #     description: "Scheduled arrival time."
        #     tests:
        #       - name: not_null
        #   - name: arr_time
        #     description: "Actual arrival time."
        #     tests:
        #       - name: not_null
        #   - name: arr_delay
        #     description: "Delay at arrival."
        #     tests:
        #       - name: not_null
        #   - name: cancelled
        #     description: "1 if flight cancelled, 0 if not."
        #     tests:
        #       - name: not_null
        #   - name: cancellation_code
        #     description: "Reason for cancellation."
        #     tests:
        #       - name: accepted_values
        #         args:
        #           values: ["A", "B", "C", "D"]
        #   - name: diverted
        #     description: "1 if flight diverted, 0 if not."
        #     tests:
        #       - name: not_null
        #   - name: crs_elapsed_time
        #     description: "Scheduled elapsed time in minutes."
        #     tests:
        #       - name: not_null
        #   - name: actual_elapsed_time
        #     description: "Actual elapsed time in minutes."
        #     tests:
        #       - name: not_null
        #   - name: air_time
        #     description: "Actual time in the air in minutes."
        #     tests:
        #       - name: not_null
        #   - name: distance
        #     description: "Distance between origin and destination in miles."
        #     tests:
        #       - name: not_null
        #   - name: carrier_delay
        #     description: "Delay due to carrier in minutes."
        #     tests:
        #       - name: not_null
        #   - name: weather_delay
        #     description: "Delay due to weather in minutes."
        #     tests:
        #       - name: not_null
        #   - name: nas_delay
        #     description: "
models:
    - name: stg_flightdata
      description: >
        Flights delay of USA between 